In [4]:
import pandas as pd

In [8]:
rails = pd.read_html('https://www.cia.gov/library/publications/the-world-factbook/fields/2121.html')

In [9]:
df=pd.DataFrame(rails[0])
df.columns = df.iloc[0]
df=df.reindex(df.index.drop(0))

In [27]:
df.head(200)

0                              Country      rails
1                              Albania      677.0
2                              Algeria     3973.0
3                               Angola     2852.0
4                            Argentina    36917.4
5                              Armenia      780.0
6                            Australia    33343.0
7                              Austria     5800.0
8                           Azerbaijan     2944.3
9                           Bangladesh     2460.0
10                             Belarus     5528.0
11                             Belgium     3592.0
12                               Benin      438.0
13                             Bolivia     3504.0
14              Bosnia and Herzegovina      965.0
15                            Botswana      888.0
16                              Brazil    29849.9
17                            Bulgaria     5114.0
18                        Burkina Faso      622.0
19                               Burma     5031.0
20                            Cambodia      642.0
21                            Cameroon      987.0
22                              Canada    77932.0
23                               Chile     7281.5
24                               China   124000.0
25                    Christmas Island       18.0
26                            Colombia     2141.0
27   Congo, Democratic Republic of the     4007.0
28              Congo, Republic of the      510.0
29                          Costa Rica      278.0
30                       Cote d'Ivoire      660.0
..                                 ...        ...
109                             Serbia     3809.0
110                           Slovakia     3580.0
111                           Slovenia     1229.0
112                       South Africa    20986.0
113                        South Sudan      248.0
114                              Spain    16101.5
115                          Sri Lanka     1562.0
116                              Sudan     7251.0
117                             Sweden    14127.0
118                        Switzerland     5651.5
119                              Syria     2052.0
120                             Taiwan     1613.1
121                         Tajikistan      680.0
122                           Tanzania     4567.0
123                           Thailand     4127.0
124                               Togo      568.0
125                            Tunisia     2173.0
126                             Turkey    12008.0
127                       Turkmenistan     5113.0
128                             Uganda     1244.0
129                            Ukraine    21733.0
130                     United Kingdom    16837.0
131                      United States   293564.2
132                            Uruguay     1673.0
133                         Uzbekistan     4642.0
134                          Venezuela      447.0
135                            Vietnam     2600.0
136                              World  1148186.0
137                             Zambia     3126.0
138                           Zimbabwe     3427.0

[138 rows x 2 columns]

In [12]:
df['rails']=df['RAILWAYS(KM)']
df['rails']=df['RAILWAYS(KM)'].str.split('k', n = 1, expand = True)

In [13]:
df['rails'] = df['rails'].replace({'[A-Za-z]':''}, regex=True)

In [15]:
df['rails'] = df['rails'].replace({'[:]':''}, regex=True)

In [19]:
df['rails'] = df['rails'].replace({'[,]':''}, regex=True)

In [21]:
df['rails'] = pd.to_numeric(df['rails'], errors='coerce')

In [22]:
df=df.drop(df.columns[[1]], axis=1)

In [24]:
df.to_pickle('rails')

In [28]:
df.isna().sum()

0
Country    0
rails      0
dtype: int64